version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - javascript
    groups:
      npm-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:30"
    open-pull-requests-limit: 2
    labels:
      - dependencies
      - github_actions
    groups:
      github-actions-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
