server {
  listen       80;
  server_name  localhost;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  # Optional: pass API requests to local host (not used inside container in prod)
  location /v1/ {
    add_header Access-Control-Allow-Origin *;
    try_files $uri $uri/ /index.html;
  }

  gzip on;
  gzip_types text/plain application/javascript text/css application/json;
}
