export const US_INSURANCE_CARRIERS: string[] = [
  '21st Century Insurance',
  'AAA Insurance',
  'Acuity Insurance',
  'AIG',
  'Alfa Insurance',
  'Allied Insurance',
  'Allstate',
  'AmTrust Financial',
  'American Family Insurance',
  'American National',
  'Amica Mutual',
  'Arbella Insurance',
  'Arrowhead General Insurance',
  'Auto-Owners Insurance',
  'Bankers Insurance',
  'Berkley Insurance',
  'Berkshire Hathaway GUARD',
  'Bristol West',
  'California Casualty',
  'Cameron Mutual',
  'Capitol Preferred Insurance',
  'Central Insurance',
  'Chubb',
  'Cincinnati Insurance',
  'Clearcover',
  'Columbia Insurance Group',
  'Concord Group Insurance',
  'COUNTRY Financial',
  'CSE Insurance Group',
  'CURE Auto Insurance',
  'Dairyland',
  'Donegal Insurance Group',
  'Edison Insurance',
  'Elephant Insurance',
  'EMC Insurance',
  'Encompass Insurance',
  'Erie Insurance',
  'Farm Bureau Insurance',
  'Farmers Insurance',
  'Federated Mutual Insurance',
  'Florida Peninsula Insurance',
  'Foremost Insurance',
  'Frankenmuth Insurance',
  'GEICO',
  'Genworth',
  'Goodville Mutual',
  'Grange Insurance',
  'Great American Insurance Group',
  'Great Northern Insurance',
  'Hanover Insurance',
  'Hastings Mutual',
  'Hippo Insurance',
  'Homesite Insurance',
  'Horace Mann',
  'Hudson Insurance Group',
  'IMT Insurance',
  'Integrity Insurance',
  'Jewelers Mutual',
  'Kemper',
  'Kingstone Insurance',
  'Liberty Mutual',
  'Lighthouse Property Insurance',
  'Main Street America',
  'MAPFRE Insurance',
  'Markel',
  'Mercury Insurance',
  'MetLife Auto & Home',
  'Mid-Century Insurance',
  'Midland National',
  'Milbank Insurance',
  'MMG Insurance',
  'National General Insurance',
  'Nationwide',
  'NJM Insurance',
  'Norfolk & Dedham',
  'North Star Mutual',
  'NYCM Insurance',
  'Occidental Fire & Casualty',
  'Ohio Mutual',
  'Oklahoma Farm Bureau',
  'Old Republic',
  'Openly',
  'Oregon Mutual',
  'Palisades Insurance',
  'PEMCO',
  'Plymouth Rock Assurance',
  'Preferred Mutual',
  'Progressive',
  'PURE Insurance',
  'QBE Insurance',
  'Quincy Mutual',
  'Safeco',
  'Safety Insurance',
  'Sagesure',
  'Selective Insurance',
  'Shelter Insurance',
  'Southern Farm Bureau',
  'State Auto',
  'State Farm',
  'Stillwater Insurance',
  'The General',
  'The Hartford',
  'The Hanover',
  'The Travelers Companies',
  'Thimble',
  'Titan Insurance',
  'Toggle Insurance',
  'Tokio Marine America',
  'Tower Hill Insurance',
  'Transamerica',
  'Travelers',
  'Trexis Insurance',
  'Truck Insurance Exchange',
  'USAA',
  'Utica National',
  'Vermont Mutual',
  'Wawanesa',
  'West Bend Mutual',
  'Western National Insurance',
  'Westfield Insurance',
  'Wright National Flood Insurance',
  'WRS Insurance',
  'Zurich North America'
].sort((a, b) => a.localeCompare(b))
